### ISSUE TITLE
Support of last DropNet version

### ISSUE THREAD

**Issue by delfuria** [uluhonolulu/DropnetExt#1]
Hi,
i'm trying to use this extensions with the las version of DropNet (1.10.23) but i get a lot of compile errors.
Thanks

**Comment by uluhonolulu** [comment]
Hi,

Sorry for not being clear, I didn't have time to publish it properly. In order to make it copilable, you'll need to do two things. 1: install the FubuCore package; 2: remove the [NotNull] attribute (I used it to make Resharper happy).

Hope that helps.
